Draft Modul PJK-05 dan 06
Lab-SSTK/Modul-Praktikum pull request #2
Opened 2023-10-14 16:37 UTC by yudofalc

Ini draft modul PJK-05 dan 06. Aku sesuaikan langkah dan tabel percobaannya. Semoga perkiraanku tepat agar praktikumnya bisa selesai selama 2 jam :)

2023-10-15 07:47 UTC, shakidc requested changes
Judul:
Protokol Komunikasi Data <i>Asynchronous</i> berbasis Mikrokontroler

Tujuan:
1. Mengenal dan memahami protokol komunikasi data <i>asynchronous</i> berbasis mikrokontroler
2. Mengenal dan memahami prinsip kerja protokol komunikasi UART dan MODBUS pada Mikrokontroler

Kompetensi Dasar:
1. Rangkaian Listrik
2. Dasar Informatika
3. Elektronika Analog
4. Pengolahan Data
5. Elektronika Digital
6. Jaringan Komunikasi

Dasar Teori

Kalimat ketiga: Perangkat yang menggunakan protokol UART dapat terhubung langsung pada perangkat lain yang juga mendukung protokol UART secara <i>wired</i> dan juga secara <i>wireless</i> dengan menggunakan modul RF433[5], <i>bluetooth</i>, Wi-Fi, dll.
Kalimat keempat: bukan <i>clock</i> tapi <i>baudrate</i>. <i>clock</i> tidak harus sama karena prinsip <i>asynchronous</i>

Percobaan:

Percobaan 5: itu python yg ngirim data gak bisa ru, karena udah kepake rx nya arduino sama PSoC, port nya udah ketutup. lebih baik dibikin 3 percobaan aja, Ardu-PSoC, Ardu-Laptop, PSoC-Laptop. untuk penampil datanya ntar kalau yg board jadi receiver di serial monitor, kalau laptop yg jadi receiver di terminal.

2023-10-15 07:54 UTC, shakidc requested changes
Judul:
Protokol Komunikasi Data <i>Synchronous</i> berbasis Mikrokontroler

Tujuan:
1. Mengenal dan memahami protokol komunikasi data <i>synchronous</i> berbasis mikrokontroler
2. Mengenal dan memahami prinsip kerja protokol komunikasi I2C dan SPI pada Mikrokontroler

Kompetensi Dasar:
1. Rangkaian Listrik
2. Dasar Informatika
3. Elektronika Analog
4. Pengolahan Data
5. Elektronika Digital
6. Jaringan Komunikasi

Dasar Teori
kurang dataframe dari SPI

Percobaan:

Percobaan: 
-Data yang dikirim di tiap percobaan jadiin 2 buah aja biar gak kebanyakan
+Tambah 2 percobaan cross board Ardu Master - PSoC Slave sama PSoC Master - Ardu Slave untuk tiap protokol, tapi datanya 1 jenis aja yg dikirim

2023-10-15 13:01 UTC, yudofalc commented
Percobaan 5 itu enggak ketutup mas serialnya. Alur datanya kan kayak gini:

Laptop 1 -> Arduino -> PSoC -> Laptop 2

Tx -> Rx / Tx -> Rx / Tx -> Rx

Pake Software serial aja arduinonya mas, harusnya aman sih. Jadi Tx / Rx ardu - laptop itu kepisah sama Tx / Rx ardu - PSoC

2023-10-15 13:58 UTC, yudofalc commented
Sebenernya aku bingung cara mengurangi jumlah percobaan yang SPI PSoC :)

2023-10-15 14:06 UTC, shakidc commented
> Percobaan 5 itu enggak ketutup mas serialnya. Alur datanya kan kayak gini:
> 
> Laptop 1 -> Arduino -> PSoC -> Laptop 2
> 
> Tx -> Rx / Tx -> Rx / Tx -> Rx
> 
> Pake Software serial aja arduinonya mas, harusnya aman sih. Jadi Tx / Rx ardu - laptop itu kepisah sama Tx / Rx ardu - PSoC

berarti 2 board 2 laptop? bisa sih, tapi itu ntaran aja di post-test ru, kasih 1 1 dulu aja laptop-board.

2023-10-15 14:07 UTC, shakidc commented
> Sebenernya aku bingung cara mengurangi jumlah percobaan yang SPI PSoC :)

variasi data yang dikirimin jadiin 2 aja kayak UART, kalau dengan variasi data yang sekarang itu jadi kelamaan ntar kombinasi percobaannya --"

2023-10-15 18:48 UTC, yudofalc commented
PJK-05 udah aku revisi mas isinya, coba di cek lagi. Yang modul-06 belum aku revisi lagi, belum sempat. Nanti pagi deh atau malem wkwk

2023-10-16 03:50 UTC, shakidc commented
[Draft PJK-05.docx](https://github.com/Lab-SSTK/Modul-Praktikum/files/12911864/Draft.PJK-05.docx)

percobaan 5 sama percobaan 6 kalau alur datanya kayak gitu berarti lebih baik jadi 1 percobaan cross board aja ru, karena udah include semua.

Laptop1(Tx)->Ardu(Rx,Tx)->PSoC(Rx,Tx)->Laptop2(Rx)

2023-10-16 15:57 UTC, yudofalc commented
Sudah aku merge ya mas percobaan 5 dan 6-nya untuk PJK-05. Tapi contoh kodingan python untuk terima masukan user dan mengirimkannya lewat PySerial belum aku kasih contohnya. 

Pilihan Percobaan 5 (Pengiriman data dari python ke MCU via PySerial:
1.  Apakah seperti yang ada di modul sekarang?
2.  Dibuat ada perintah untuk menerima masukan dari user menggunakan fungsi input di Python?

2023-10-17 04:28 UTC, shakidc commented
> Sudah aku merge ya mas percobaan 5 dan 6-nya untuk PJK-05. Tapi contoh kodingan python untuk terima masukan user dan mengirimkannya lewat PySerial belum aku kasih contohnya.
> 
> Pilihan Percobaan 5 (Pengiriman data dari python ke MCU via PySerial:
> 
> 1. Apakah seperti yang ada di modul sekarang?
> 2. Dibuat ada perintah untuk menerima masukan dari user menggunakan fungsi input di Python?

dibikin statis aja dulu ru, jadi udah ditentuin dari kodingannya apa yg mau dikirim, kalau yg dinamisnya itu biar mereka eksplor sendiri aja. Harusnya itu gak terlalu ribet kalau mau coba2 sendiri karena tinggal tambahin fungsi input() doang di variabel yg mau dipake buat kirim data.

2023-10-17 08:59 UTC, yudofalc commented
Okey, berarti udah bener ya isi modul PJK-05 yang aku buat? Kurang yang bagian MODBUS ya(?) Sementara ini, ada yang perlu aku ubah2 lagi ga mas? Dari langkah percobaan sampai tabel percobaannya

2023-10-18 16:11 UTC, yudofalc commented
Sudah aku buat revisi modul PJK-06nya mas, bisa di review. Itu percobaan antar boardnya aku pisah-pisah. 

Aku masih bingung input datanya itu mau dari user (python via PySerial) atau built-In di kodingan masternya(?)

2023-10-18 18:36 UTC, shakidc approved these changes
sip kurang yg modbus aja

2023-10-18 18:37 UTC, shakidc approved these changes
sejauh ini oke, tinggal dirapiin aja sebelum release pdf nya

2023-10-21 15:29 UTC, yudofalc commented
> sip kurang yg modbus aja

Variasi dan kodingan yang dipake untuk modbus itu ada dimana ya? Aku liat di word nya belum ke update untuk bagian modbus

2023-10-22 01:55 UTC, closed without merging